language: rust
rust:
  - 1.18.0
  - stable
script:
  - set -x
  - cargo build --no-default-features
  - cargo build --no-default-features --feature "color"
  - cargo test --all --verbose
  - cd fuzz
  - cargo build --all --verbose
