[package]
name = "codegen"
version = "0.1.0"
authors = ["RazrFalcon <razrfalcon@gmail.com>"]
license = "MIT/Apache-2.0"

[dependencies]
phf = "0.7.22"
phf_codegen = "0.7.22"
itertools = "0.7"
derive-error = "0.0.4"
